biolib_version: 2

modules:
    main:
        image: 'dockerhub://robmurs/ribdif:latest'
        working_directory: /ribdif/
        input_files: []
        output_files:
            - COPY /results/ /
        source_files: []

arguments:
    -   key: --genus # required
        description: "The genus you want to search within. E.g. 'Staphylococcus' OR 'Staphylococcus aurea' if wanting to use a species" # required
        type: text # required
        required: true # optional, default is true
        
    -   key: --ignore-sp # required
        description: "Ignore genomes with unspecified species (i.e. their species is 'sp.')"
        type: toggle # required
        required: False # optional, default is true
        default_value: "off"
        options:
            'on': "on"
            'off': "off"
        
    -   key: --primers # required
        description: "Path to custom primer-file (if using), must be a tab seperated file with name, forward and reverse primers. Default primers are 16S v3v4 and v1v9"
        type: file # required
        default_value: "default.primers"
        required: False # optional, default is true
        
# =============================================================================
#     -   key: --ani # required
#         description: "ANI is off by default, turn on if you care about individual genomes. The $genus-summary.csv-file will only contain a list of genomes when off. Mutually exclusive with --whole-genome"
#         type: toggle # required
#         required: False # optional, default is true
#         default_value: "off"
#         options:
#             'on': "on"
#             'off': "off"
# =============================================================================
        
    -   key: --frag # required
        description: "Allow use of fragmented genomes. Full genomes are recomended/requierd for detecting all 16S-genes, use with caution."
        type: toggle # required
        required: False # optional, default is true
        default_value: "off"
        options:
            'on': "on"
            'off': "off"

    -   key: --msa # required
        description: "Make multiple sequence alignment and trees"
        type: toggle # required
        required: False # optional, default is true
        default_value: "off"
        options:
            'on': "on"
            'off': "off"

    -   key: --id # required
        description: "Identity to cluster amplicons at if not using the deafult 1.00 (e.g. .99)."
        type: number # required
        required: False # optional, default is true

    -   key: --whole-genome # required
        description: "Indicate the custom primers given are to be run on the whole genome so no barrnap, msa, ani (Required if your primers are non 16S)."
        type: toggle # required
        required: False # optional, default is true
        default_value: "off"
        options:
            'on': "on"
            'off': "off"

remote_hosts: 
    -   ftp.ncbi.nih.gov

description_file: README.md

license_file: LICENSE


#F64cl6qis0lNLuGjFUCv5jjN2vwe8xSbMtFnVWYhULI